name: Build🔨 and Test🧪

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "oracle"
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew test
